require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Metrics/BlockLength:
  Exclude:
  - spec/**/*_spec.rb

Layout/MultilineMethodCallIndentation:
  Exclude:
  - spec/**/*_spec.rb
